<?php

namespace Tests\Feature;

use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UserQuizStatusTest extends TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->quiz_id = 1;
        $this->user_id = 1;

        factory(\App\UserAnswerSet::class )->create(

            array(
                'user_quiz_id' => 2,
                'question_id' => 1,
                'user_answer_set' =>'10',
                'is_valid' => 1
            )
        );

        factory(\App\UserAnswerSet::class )->create(
            array(
                'user_quiz_id' => 1,
                'question_id' => 1,
                'user_answer_set' =>'10',
                'is_valid' => 1
            )
        );

        factory(\App\UserAnswerSet::class )->create(
            array(
                'user_quiz_id' => 1,
                'question_id' => 2,
                'user_answer_set' =>'010',
                'is_valid' => 0
            )
        );

        factory(\App\UserQuiz::class)->create(array('quiz_id'=>1, 'user_id' => 1));
        factory(\App\Question::class, 5)->create();

    }

    public function test_user_quiz_exist(){

        $this->assertCount(1, \App\UserQuiz::all());
        $incomplete =  ( new \App\UserQuiz)->quizIsIncomplete($this->user_id, $this->quiz_id);
        $this->assertTrue($incomplete);
    }

    public function test_get_incomplete_user_quiz_id()
    {
        factory(\App\UserQuiz::class)->create(array('quiz_id'=>2, 'user_id' => 1));
        $userQuizId =  ( new \App\UserQuiz)->getIncompleteUserQuizId($this->user_id, $this->quiz_id);
        $this->assertEquals(1, $userQuizId);
    }

    public function test_nr_of_question_answered()
    {
        $userQuizId =  ( new \App\UserQuiz )->getIncompleteUserQuizId($this->user_id, $this->quiz_id);

        $this->assertEquals(2, (new \App\UserAnswerSet)->nrOfQuestionAnswered($userQuizId));
    }

    public function test_user_quiz_progress()
    {

        $totalNrOfQuestions = 5;
        $nrOfQuestionsAnswered = 2;
        $this->assertEquals(40, (new \App\Quiz)->quizProgress($totalNrOfQuestions, $nrOfQuestionsAnswered ) );
    }


    public function user_can_reset_quiz()
    {
        $response = $this->call('get','/resetQuiz/1');
        $response->assertStatus(200);
    }





}
